### ISSUE TITLE
Robust ANOVA error in latest flatpak version

### ISSUE THREAD

**Issue by HRDudeness** [jamovi/walrus#1]
Getting the following error when I try to run a robust ANOVA:

```
Error: package ‘WRS2’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
private$.run()
WRS2::t1way
getExportedValue(pkg, name)
asNamespace(ns)
getNamespace(ns)
tryCatch(loadNamespace(name), error = function(e) stop(e))
tryCatchList(expr, classes, parentenv, handlers)
tryCatchOne(expr, names, parentenv, handlers[[1]])
value[[3]](cond)
```

jamovi 0.9.5.1 (flatpak)
walrus 1.0.2

**Comment by HRDudeness** [comment]
Update: the bug seems to be fixed with the github version of walrus. I've downloaded, compiled and installed this version and Robust ANOVA works without errors. Maybe it can be pushed into the jamovi library?

**Comment by jonathon-love** [comment]
ah yup, thanks for reporting. yeah, it just needs to be rebuilt for the flatpak version.

i'll get to that shortly (but ping me if i forget)

with thanks

**Comment by jonathon-love** [comment]
ok, i've updated it now. thanks for bringing this to my attention.
