### ISSUE TITLE
Robust t-tests does not run

### ISSUE THREAD

**Issue by ericcfields** [jamovi/walrus#2]
When I try to run a robust t-test (any of the options) it returns NaN for the t-value and at the bottom of the table says "there is no package called 'reshape'".

I'm using jamovi version 1.0.6.0 and Walrus version 1.0.2 running in Windows 10. This doesn't seem to be specific to any dataset, but, for example, I can produce it with the harpo dataset in the jamovi data library.

**Comment by jonathon-love** [comment]
hi,

this is a little puzzling to me. take a look here:

`C:\Users\username\AppData\Roaming\jamovi\modules\walrus\R`

and tell me what's there. there *should* be a folder called `reshape`, and it should contain stuff.

if it's missing, something must have gone wrong in the module installation process. try uninstalling and reinstalling (walrus).

cheers

jonathon

**Comment by ericcfields** [comment]
Thanks, reinstalling worked. Weird, because I thought I had already tried that, but maybe I had just tried updating jamovi. Sorry for wasting your time!
